music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    path('', views.IndexView.as_view(), name="index"),

    # /music/id/
    path("<pk>/", views.DetailView.as_view(), name="detail"),
    path('album/add/', views.AlbumCreate.as_view(), name="album-add")


]

website2/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
    path('', views.redirect, name="root")
]

music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.id})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Album


class IndexView(ListView):
    template_name = 'music/index.html'
    context_object_name = "all_albums"
    queryset = Album.objects.all()

    # def get_queryset(self):
    #     return Album.objects.all()


class DetailView(DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

website2/views.py
from django.http import HttpResponse


def redirect(request):
    return HttpResponse("<p>Direction to App : <a href='music'>Music</a></p>")

music/templates/music/album_form.html
{% extends 'music/base.html' %}

{% block body %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'music/form_template.html' %}

        <button type="submit" class="btn btn-success">Submit</button>

    </form>

{% endblock body %}

music/templates/music/base.html
<!doctype html>
<html lang="en">
<head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css"
          integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    <!--load the paths to your static files-->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <!-- <style>
      body{
    background: white url("https://raw.githubusercontent.com/buckyroberts/Viberr/master/music/static/music/images/background.png");
}

.img-resize{
    height:40vh;
    object-fit: cover;
    object-position: center center;
}

    </style> -->
</head>
<body>


    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
        <a href="{% url 'music:index' %}" class="navbar-brand"><i class="fas fa-home"></i> Viberr</a>


        <button class="navbar-toggler" data-toggle="collapse" data-target="#mynav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mynav">
            <div class="navbar-nav ml-5">
              <a href="#" class="nav-item nav-link active"><i class="fas fa-compact-disc"></i> Albums</a>
              <a href="#" class="nav-item nav-link"><i class="fas fa-music  "></i> Songs</a>

            </div>
            <form action="" class="form-inline">
              <input type="search" name="" id="" class="form-control mr-2" placeholder="Search">
              <button class="btn btn-secondary">search</button>

            </form>
            <div class="navbar-nav ml-auto">

            <a href="{% url 'music:album-add' %}" class="nav-item nav-link"><i class="fas fa-plus"></i> Add Album</a>
            <a href="#" class="nav-item nav-link"><i class="fas fa-power-off "></i> Logout</a>
            </div>




        </div>

      </nav>

    <div class="container-fluid">
        {% block body %}

        {% endblock %}
    </div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block body %}

<div class="row">
    <div class="card col-lg-3 col-md-4  border-0 m-3" style="background: rgb(237, 237, 237)" >
      <img src="{{ album.album_logo }}" class="card-img-top  img-resize" alt="Album logo" style="height: 35vh;">
      <div class="card-body bg-light p-5">
        <h2 class="card-title text-primary">{{ album.album_title }} <span class="h4 text-muted">{{ album.genre }}</span></h2>
        <h3 class="card-subtitle mb-2">{{ album.artist }}</h3>
      </div>
    </div>
    <div class="col mt-5">

           <table class="table table-striped  table-hover table-secondary">
          <thead class="thead-dark">
              <tr>
                  <th scope="col">#</th>
                  <th scope="col">Song title</th>
                  <th scope="col">favorite</th>
                  <th scope="col">file type</th>
              </tr>
          </thead>
          <tbody>
          {% for song in album.song_set.all %}
              <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ song.song_title }}</td>
                  <td>
                      {% if song.is_favorite %}
                          <img src="http://i.imgur.com/b9b13Rd.png" alt="">
                      {% endif %}
                  </td>
                  <td>{{ song.file_type }}</td>
              </tr>
          {% endfor %}
          </tbody>
      </table>
    <button type="button" class="btn btn-info btn-lg ">add new song</button>



    </div>


</div>

{% endblock body %}

music/templates/music/form_template.html
{% load crispy_forms_tags %}
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-success">Save person</button>

  </form>

music/templates/music/index.html
{% extends 'music/base.html' %}

{#{% block body %}#}
{#    <h1 class="display-3">Here are all my Albums: </h1>#}
{#    <ul>#}
{#    {% for album in all_albums %}#}
{#    <li><a href="{% url 'music:detail' album.id %}">{{ album }}</a></li>#}
{#    {% endfor %}#}
{#    </ul>#}
{#{% endblock %}#}
{% block body %}
    <div class="row">


    {% for album in all_albums %}

    <div class="card col-lg-4 col-md-5 p-4 border-0 mt-3" style="background: rgb(237, 237, 237)" >
      <img src="{{ album.album_logo }}" class="card-img-top  img-resize" alt="Album logo">
      <div class="card-body bg-light">
        <h3 class="card-title text-primary">{{ album.album_title }}</h3>
        <h5 class="card-subtitle mb-2">{{ album.artist }}</h5>
        <a href="{% url 'music:detail' album.id %}" class="btn btn-primary card-link">Details</a>
        <a href="#" class="btn btn-outline-primary card-link ml-0"><i class="fas fa-star"></i></a>
        <a href="#" class="btn btn-outline-primary card-link ml-0"><i class="fas fa-trash-alt"></i></a>
      </div>
    </div>





{% endfor %}
</div><!--row-->
{% endblock body %}

templates/music/base.html
<!doctype html>
<html lang="en">
<head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css"
          integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    <!--load the paths to your static files-->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
</head>
<body>


    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
        <a href="{% url 'music:index' %}" class="navbar-brand"><i class="fas fa-home"></i> Viberr</a>


        <button class="navbar-toggler" data-toggle="collapse" data-target="#mynav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mynav">
            <div class="navbar-nav ml-5">
              <a href="#" class="nav-item nav-link active"><i class="fas fa-compact-disc"></i> Albums</a>
              <a href="#" class="nav-item nav-link"><i class="fas fa-music  "></i> Songs</a>

            </div>
            <form action="" class="form-inline">
              <input type="search" name="" id="" class="form-control mr-2" placeholder="Search">
              <button class="btn btn-secondary">search</button>

            </form>
            <div class="navbar-nav ml-auto">

            <a href="{% url 'music:album-add' %}" class="nav-item nav-link"><i class="fas fa-plus"></i> Add Album</a>
            <a href="#" class="nav-item nav-link"><i class="fas fa-power-off "></i> Logout</a>
            </div>




        </div>

      </nav>

    <div class="container-fluid">
        {% block body %}

        {% endblock %}
    </div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>